services:
  db:
    image: postgres:15
    container_name: replay_master_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replay_master_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d replay_master_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:


